default_agent: cost_estimator_agent
agents:
  cost_estimator_agent:
    name: cost_estimator_agent
    entrypoint: /home/ubuntu/sample-amazon-bedrock-agentcore-onboarding/02_runtime/deployment/invoke.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::872515288562:role/AgentCoreRole-cost_estimator_agent
      account: '872515288562'
      region: us-east-1
      ecr_repository: 872515288562.dkr.ecr.us-east-1.amazonaws.com/bedrock_agentcore-cost_estimator_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: cost_estimator_agent-KdUH315eFT
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:872515288562:runtime/cost_estimator_agent-KdUH315eFT
      agent_session_id: null
    authorizer_configuration: null
    oauth_configuration: null
